{{-- resources/views/properties/certificate-pdf.blade.php --}}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1a1a1a; margin: 0; }
    .header { background: #1a56db; color: white; padding: 20px 30px; text-align: center; }
    .header h2 { margin: 0; font-size: 20px; letter-spacing: 1px; }
    .header p { margin: 4px 0 0; font-size: 11px; opacity: .85; }
    .cert-title { text-align: center; padding: 20px; border-bottom: 3px double #1a56db; }
    .cert-title h3 { color: #1a56db; font-size: 18px; letter-spacing: 2px; text-transform: uppercase; margin: 0; }
    .body { padding: 20px 30px; }
    .row { display: flex; gap: 20px; margin-bottom: 16px; }
    .col { flex: 1; }
    table.details { width: 100%; border-collapse: collapse; }
    table.details td { padding: 6px 8px; border: 1px solid #e2e8f0; font-size: 11px; }
    table.details td.label { background: #f8fafc; font-weight: bold; color: #64748b; width: 40%; }
    .section-title { background: #1a56db; color: white; padding: 6px 10px; font-size: 11px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; margin: 16px 0 8px; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 2px solid #1a56db; display: flex; justify-content: space-between; }
    .seal-box { border: 2px dashed #1a56db; width: 100px; height: 100px; display: flex; align-items: center; justify-content: center; text-align: center; font-size: 9px; color: #1a56db; }
    .watermark { position: fixed; top: 40%; left: 50%; transform: translate(-50%,-50%) rotate(-45deg); font-size: 60px; color: rgba(26,86,219,0.05); font-weight: bold; letter-spacing: 10px; }
</style>
</head>
<body>
<div class="watermark">OFFICIAL</div>
<div class="header">
    <h2>🏛 GOVERNMENT LAND REGISTRY</h2>
    <p>Official Property Title Certificate</p>
</div>

<div class="cert-title">
    <h3>Certificate of Land Registration</h3>
    <p style="color:#64748b;font-size:11px;">Certificate No: CERT-{{ $property->survey_number }}-{{ date('Y') }}</p>
</div>

<div class="body">
    <p>This is to certify that the following land/property is registered in the Government Land Registry System as per official records:</p>

    <div class="section-title">Property Information</div>
    <table class="details">
        <tr><td class="label">Survey Number</td><td>{{ $property->survey_number }}</td><td class="label">Plot Number</td><td>{{ $property->plot_number ?? '—' }}</td></tr>
        <tr><td class="label">Land Type</td><td>{{ $property->land_type_label }}</td><td class="label">Land Use</td><td>{{ ucwords(str_replace('_',' ',$property->land_use)) }}</td></tr>
        <tr><td class="label">Area (Sq.ft)</td><td>{{ number_format($property->area_sqft, 2) }}</td><td class="label">Area (Sq.m)</td><td>{{ number_format($property->area_sqm, 2) }}</td></tr>
        <tr><td class="label">Village/Area</td><td>{{ $property->village ?? '—' }}</td><td class="label">Taluka</td><td>{{ $property->taluka }}</td></tr>
        <tr><td class="label">District</td><td>{{ $property->district }}</td><td class="label">State</td><td>{{ $property->state }}</td></tr>
        <tr><td class="label">Pincode</td><td>{{ $property->pincode }}</td><td class="label">Status</td><td>{{ ucwords(str_replace('_',' ',$property->status)) }}</td></tr>
        <tr><td class="label">Market Value</td><td>₹{{ number_format($property->market_value) }}</td><td class="label">Govt. Value</td><td>₹{{ number_format($property->government_value) }}</td></tr>
    </table>

    @if($property->currentOwner)
    <div class="section-title">Current Owner Details</div>
    <table class="details">
        <tr><td class="label">Full Name</td><td>{{ $property->currentOwner->full_name }}</td><td class="label">Owner No.</td><td>{{ $property->currentOwner->owner_number }}</td></tr>
        <tr><td class="label">ID Type</td><td>{{ ucwords(str_replace('_',' ',$property->currentOwner->id_type)) }}</td><td class="label">ID Number</td><td>{{ $property->currentOwner->id_number }}</td></tr>
        <tr><td class="label">Address</td><td colspan="3">{{ $property->currentOwner->address }}, {{ $property->currentOwner->city }}, {{ $property->currentOwner->state }}</td></tr>
    </table>
    @endif

    <div class="footer">
        <div>
            <p style="margin:0;font-size:11px;">Generated by: Land Registry System</p>
            <p style="margin:2px 0;font-size:11px;">Date: {{ now()->format('d M Y') }}</p>
            <p style="margin:2px 0;font-size:10px;color:#64748b;">This is a computer-generated document.</p>
        </div>
        <div class="seal-box">OFFICIAL<br>SEAL<br>&amp;<br>SIGNATURE</div>
    </div>
</div>
</body>
</html>
